# Generated by Django 5.0.4 on 2024-04-06 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dateBirth', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('phoneNumber', models.IntegerField(max_length=20)),
                ('dateBirth', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('idMedication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.medication')),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='patientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.patient'),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=50)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('doctorName', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('idPatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='orderProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProcedure', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('specialAssistance', models.CharField(max_length=50)),
                ('item', models.IntegerField()),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.order')),
                ('idSpecialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDiagnosticAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDiagnosticAid', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('specialAssistance', models.BooleanField()),
                ('idOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.order')),
                ('idSpecialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.person')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='doctorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.person'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('medications', models.CharField(max_length=50)),
                ('procedures', models.CharField(max_length=50)),
                ('diagnosticAids', models.CharField(max_length=50)),
                ('totalCost', models.CharField(max_length=50)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.order')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.patient')),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bloodPressure', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('pulse', models.CharField(max_length=50)),
                ('oxygenLvl', models.CharField(max_length=50)),
                ('medications', models.CharField(max_length=50)),
                ('procedures', models.CharField(max_length=50)),
                ('observations', models.CharField(max_length=50)),
                ('orderMedication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderMedication', to='HospitalApp.order')),
                ('orderProcedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderProcedure', to='HospitalApp.order')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.patient')),
            ],
        ),
    ]
