# Generated by Django 5.0.4 on 2024-04-20 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.person'),
        ),
    ]
