# Generated by Django 5.0.4 on 2024-04-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0003_alter_appointment_doctorname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctorName',
            new_name='doctor',
        ),
    ]
