# Generated by Django 5.0.4 on 2024-04-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0004_rename_doctorname_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
