# Generated by Django 5.0.4 on 2024-04-21 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0006_alter_appointment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticAid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderdiagnosticaid',
            name='nameDiagnosticAid',
        ),
        migrations.RemoveField(
            model_name='ordermedication',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='procedures',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdiagnosticaid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordermedication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordermedication',
            name='idMedication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.medication'),
        ),
        migrations.AlterField(
            model_name='orderprocedure',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderprocedure',
            name='specialAssistance',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='orderdiagnosticaid',
            name='DiagnosticAid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.diagnosticaid'),
        ),
        migrations.AlterField(
            model_name='orderprocedure',
            name='idProcedure',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.procedure'),
        ),
    ]
