# Generated by Django 5.0.4 on 2024-04-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0008_alter_medication_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateBirth',
            field=models.DateField(),
        ),
    ]
