# Generated by Django 5.0.4 on 2024-05-01 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0010_alter_orderprocedure_idspecialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdiagnosticaid',
            name='idSpecialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.person'),
        ),
    ]
