# Generated by Django 5.0.4 on 2024-05-01 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0011_alter_orderdiagnosticaid_idspecialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermedication',
            name='idOrder',
            field=models.ForeignKey(db_column='idOrder', on_delete=django.db.models.deletion.CASCADE, related_name='orderMedication_Order', to='HospitalApp.order'),
        ),
    ]
