# Generated by Django 5.0.4 on 2024-05-03 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0013_alter_orderdiagnosticaid_idorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='orderMedication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderMedication', to='HospitalApp.ordermedication'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='orderProcedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderProcedure', to='HospitalApp.orderprocedure'),
        ),
    ]
