# Generated by Django 5.0.4 on 2024-05-03 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0015_alter_visit_ordermedication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='itemMedication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemMedication', to='HospitalApp.ordermedication'),
        ),
        migrations.AddField(
            model_name='visit',
            name='itemProcedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemProcedure', to='HospitalApp.orderprocedure'),
        ),
    ]
