# Generated by Django 5.0.4 on 2024-05-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0019_alter_visit_ordermedication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermedication',
            name='item',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='itemMedication',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='itemProcedure',
            field=models.IntegerField(null=True),
        ),
    ]
