# Generated by Django 5.0.4 on 2024-05-03 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0021_alter_visit_ordermedication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='orderProcedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderProcedure', to='HospitalApp.order'),
        ),
    ]
